name: Tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Install dependencies using the build.yml workflow
      - name: Install Dependencies
        uses: ./.github/workflows/actions/install_dependencies/build.yml

      # Step 3: Activate the virtual environment and run pytest
      - name: Run Pytest
        run: |
          . .venv/bin/activate  # Activate the virtual environment
          pytest                # Run pytest within the activated environment
