name: Tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Read Python version from .python-version file
      - name: Read Python Version
        id: python_version
        run: echo "VERSION=$(cat .python-version)" >> $GITHUB_ENV

      # Step 3: Set up Python with the version from .python-version
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.VERSION }}

      # Step 4: Install Rye
      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.42.0" RYE_INSTALL_OPTION="--yes" bash
          echo "${HOME}/.rye/bin" >> $GITHUB_PATH  # Add Rye to PATH
          # Verify that Rye was installed correctly
          rye --version

      # Step 5: Install Dependencies using Rye
      - name: Install Dependencies
        run: |
          rye --version  # Check if Rye is available
          rye sync

      # Step 6: Activate the virtual environment and run pytest
      - name: Run Pytest
        run: |
          . .venv/bin/activate  # Activate the virtual environment
          pytest                # Run pytest within the activated environment
