name: "Install Dependencies with Rye"
description: "Action to build the project dependencies using Rye and the Python version specified in .python-version"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Read Python version from .python-version file
      - name: Read Python Version
        id: python_version
        run: echo "VERSION=$(cat .python-version)" >> $GITHUB_ENV

      # Step 3: Set up Python with the version from .python-version
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.VERSION }}

      # Step 4: Install Rye
      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "${HOME}/.rye/bin" >> $GITHUB_PATH  # Add Rye to PATH

      # Step 5: Install Dependencies using Rye
      - name: Install Dependencies
        run: rye sync
